### ISSUE TITLE
What is the stable version of JsonRestFixture if at all we want to use in production and what is the minimum JDK version and RestFixture version that is required?

### ISSUE THREAD

**Issue by kadimulam** [dnygaard/JsonRestFixture#5]

**Comment by dnygaard** [comment]
I see the last synchronisation with RestFixture was done October 2014 or earlier. I also see I tested that version with Java 1.7.

The current version includes the version of RestFixture that was current at that time. (RestFixture appeared dormant at that time). You don't need to install RestFixture too. But, if you want a new release of RestFixture, you can clone the latest RestFixture and add my JsonRestFixture and helperclasses + modify the pom-file yourself.

I believe the current version should work as is, but limited to the old version of RestFixture and old versions of the support libraries.

See issue #4. - Is planned but waiting for some available time.

**Comment by kadimulam** [comment]
In pom.xml i can see smartrics-RestClient.2.1.jar. I am assuming, this needs to be updated to a higher version (4.1), if we need to have updated RestFixture. Is that correct?

**Comment by dnygaard** [comment]
Yes, correct. 

Den 11. april 2016 15:35:59 CEST, skrev kadimulam notifications@github.com:

> In pom.xml i can see smartrics-RestClient.2.1.jar. I am assuming, this
> needs to be updated to a higher version (4.1), if we need to have
> updated RestFixture. Is that correct?
> 
> ---
> 
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/dnygaard/JsonRestFixture/issues/5#issuecomment-208346544

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by kadimulam** [comment]
Ok, do we have copyright permission to modify the RestFixture version in pom.xml if at all we want to use code in production?

**Comment by dnygaard** [comment]
On the JsonRestFixture code, do whatever you like, no restrictions for usage or modifications, but also no liabilities on my part, I share it here on GitHub for anyone who need to use it. For RestFixture and the other libraries: check the copyrights, but I expect the copyrights are similar.
